apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_label }}-service
  labels:
    app: {{ .Values.app_label }}
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ .Values.app_label }}
