name: Mention Notifier

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Mention Notify
        uses: abeyuya/actions-mention-to-slack@v2.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_MENTION }}
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          bot-name: "GitHub Mention알리미"
          run-id: ${{ github.run_id }}

      - name: Slack-Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          author_name: GitHub Mension Sync
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure()
