# This is a basic workflow to help you get started with Actions

name: Metion-to-Slack

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    issues:
        types: [opened]
    issue_comment:
        types: [created]
    pull_request:
        types: [opened, assigned]
    pull_request_review:
        types: [submitted]
    pull_request_review_comment:
        types: [created]

jobs:
    mention-to-slack:
        runs-on: ubuntu-latest
        steps:
            - name: Run
              uses: abeyuya/actions-mention-to-slack@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/mention-to-slack.yml
                  slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
                  icon-url: https://img.icons8.com/color/256/000000/github-2.png
                  bot-name: "GitHub Bot"
                  run-id: ${{ github.run_id }}
