# This is a basic workflow to help you get started with Actions

name: PR test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    pull_request:
        branches:
            - master
            - env

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    Pytest:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version:
                    - 3.x
        timeout-minutes: 60

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - name: Prerequeist
              run: |
                  pip3 install --upgrade pip setuptools
                  pip3 install pytest pytest-cov --no-cache --user
                  pip3 install -r requirements.txt --user

            - name: test with pytest
              run: python3 -m pytest --cov-report=xml --cov=./ tests/*

            - name: upload coverage to codecov
              uses: codecov/codecov-action@v1.0.10
              with:
                  file: ./coverage.xml
                  flags: tests
                  fail_ci_if_error: true

            - name: Slack-Notification
              uses: 8398a7/action-slack@v3
              with:
                  status: ${{job.status}}
                  fields: repo,message,commit,author,action,eventName,ref,workflow
                  author_name: PR Notification
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
              if: failure()
