# This is a basic workflow to help you get started with Actions

name: Lint & Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
      - master
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: prerequisite
      run: echo "prerequisite"

    - name: linting
      run: echo "Lint Test"

    - name: Test
      run: echo "Test"

    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: ". --check"
   
    - name: Slack-Notification
      uses: 8398a7/action-slack@v2.6.0
      with:
        status: ${{job.status}}
        fields: repo,message,commit,author,action,eventName,ref,workflow
        author_name: 린트 알리미
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always()
